name: times
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  intl: ^0.17.0
  arabic_numbers: ^1.0.0
  provider: ^6.0.3

  cupertino_icons: ^1.0.2
  url_launcher: 6.1.10
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/flags/

  fonts:
    - family: rudaw
      fonts:
        - asset: assets/fonts/rudawregular2.ttf