import '../services/countries.dart';

class Country {
  static List<Countries> locations = [
    Countries(
      id: 1,
      name: 'بەریتانیا',
      flag: 'icons/flags/png/gb.png',
      url: 'Europe/London',
      utcHour: 1,
      utcMinutes: 0,
    ),
    Countries(
      id: 1,
      name: 'ئەمریکا + کەنەدا',
      flag: 'icons/flags/png/us.png',
      url: 'America/New_York',
      utcHour: -4,
      utcMinutes: 0,
    ),
    Countries(
      id: 1,
      name: 'عێراق',
      flag: 'icons/flags/png/iq.png',
      url: 'Asia/Baghdad',
      utcHour: 3,
      utcMinutes: 0,
    ),
    Countries(
      id: 1,
      name: 'هیندستان',
      flag: 'icons/flags/png/in.png',
      url: 'Asia/Colombo',
      utcHour: 5,
      utcMinutes: 30,
    ),
    Countries(
      id: 1,
      name: 'تورکیا',
      flag: 'icons/flags/png/tr.png',
      url: 'Turkey',
      utcHour: 3,
      utcMinutes: 0,
    ),
    Countries(
      id: 1,
      name: 'سوید',
      flag: 'icons/flags/png/se.png',
      url: 'Europe/Stockholm',
      utcHour: 2,
      utcMinutes: 0,
    ),
    Countries(
      id: 1,
      name: 'یابان',
      flag: 'icons/flags/png/jp.png',
      url: 'Asia/Tokyo',
      utcHour: 9,
      utcMinutes: 0,
    ),
    Countries(
      id: 1,
      name: 'چین',
      flag: 'icons/flags/png/cn.png',
      url: 'Asia/Ulaanbaatar',
      utcHour: 8,
      utcMinutes: 0,
    ),
    Countries(
      id: 1,
      name: 'ئەڵمانیا',
      flag: 'icons/flags/png/de.png',
      url: 'Europe/Berlin',
      utcHour: 2,
      utcMinutes: 0,
    ),
    Countries(
      id: 1,
      name: 'میسر',
      flag: 'icons/flags/png/eg.png',
      url: 'Africa/Cairo',
      utcHour: 2,
      utcMinutes: 0,
    ),
    Countries(
      id: 1,
      name: 'فەڕەنسا',
      flag: 'icons/flags/png/fr.png',
      url: 'Europe/Paris',
      utcHour: 2,
      utcMinutes: 0,
    ),
    Countries(
      id: 1,
      name: 'سعودیا',
      flag: 'icons/flags/png/sa.png',
      url: 'Asia/Riyadh',
      utcHour: 3,
      utcMinutes: 0,
    ),
    Countries(
      id: 1,
      name: 'نەرویج',
      flag: 'icons/flags/png/no.png',
      url: 'Europe/Oslo',
      utcHour: 2,
      utcMinutes: 0,
    ),
    Countries(
      id: 1,
      name: 'یۆنان',
      flag: 'icons/flags/png/gr.png',
      url: 'Europe/Athens',
      utcHour: 3,
      utcMinutes: 0,
    ),
    Countries(
      id: 1,
      name: 'ئەفغانستان',
      flag: 'icons/flags/png/af.png',
      url: 'Asia/Kabul',
      utcHour: 4,
      utcMinutes: 30,
    ),
  ];
}
