import '../services/countries.dart';

class Country {
  static List<Countries> locations = [
    Countries(
      id: 1,
      name: 'بەریتانیا',
      flag: 'assets/images/flags/gb.webp',
      url: 'Europe/London',
      utcHour: 1,
      utcMinutes: 0,
    ),
    Countries(
      id: 1,
      name: 'ئەمریکا + کەنەدا',
      flag: 'assets/images/flags/us.webp',
      url: 'America/New_York',
      utcHour: -4,
      utcMinutes: 0,
    ),
    Countries(
      id: 1,
      name: 'عێراق',
      flag: 'assets/images/flags/iq.webp',
      url: 'Asia/Baghdad',
      utcHour: 3,
      utcMinutes: 0,
    ),
    Countries(
      id: 1,
      name: 'هیندستان',
      flag: 'assets/images/flags/in.webp',
      url: 'Asia/Colombo',
      utcHour: 5,
      utcMinutes: 30,
    ),
    Countries(
      id: 1,
      name: 'تورکیا',
      flag: 'assets/images/flags/tr.webp',
      url: 'Turkey',
      utcHour: 3,
      utcMinutes: 0,
    ),
    Countries(
      id: 1,
      name: 'سوید',
      flag: 'assets/images/flags/se.webp',
      url: 'Europe/Stockholm',
      utcHour: 2,
      utcMinutes: 0,
    ),
    Countries(
      id: 1,
      name: 'یابان',
      flag: 'assets/images/flags/jp.webp',
      url: 'Asia/Tokyo',
      utcHour: 9,
      utcMinutes: 0,
    ),
    Countries(
      id: 1,
      name: 'چین',
      flag: 'assets/images/flags/cn.webp',
      url: 'Asia/Ulaanbaatar',
      utcHour: 8,
      utcMinutes: 0,
    ),
    Countries(
      id: 1,
      name: 'ئەڵمانیا',
      flag: 'assets/images/flags/de.webp',
      url: 'Europe/Berlin',
      utcHour: 2,
      utcMinutes: 0,
    ),
    Countries(
      id: 1,
      name: 'میسر',
      flag: 'assets/images/flags/eg.webp',
      url: 'Africa/Cairo',
      utcHour: 2,
      utcMinutes: 0,
    ),
    Countries(
      id: 1,
      name: 'فەڕەنسا',
      flag: 'assets/images/flags/fr.webp',
      url: 'Europe/Paris',
      utcHour: 2,
      utcMinutes: 0,
    ),
    Countries(
      id: 1,
      name: 'سعودیا',
      flag: 'assets/images/flags/sa.webp',
      url: 'Asia/Riyadh',
      utcHour: 3,
      utcMinutes: 0,
    ),
    Countries(
      id: 1,
      name: 'نەرویج',
      flag: 'assets/images/flags/no.webp',
      url: 'Europe/Oslo',
      utcHour: 2,
      utcMinutes: 0,
    ),
    Countries(
      id: 1,
      name: 'یۆنان',
      flag: 'assets/images/flags/gr.webp',
      url: 'Europe/Athens',
      utcHour: 3,
      utcMinutes: 0,
    ),
    Countries(
      id: 1,
      name: 'ئەفغانستان',
      flag: 'assets/images/flags/af.webp',
      url: 'Asia/Kabul',
      utcHour: 4,
      utcMinutes: 30,
    ),
  ];
}
