import '../services/countries.dart';

class Country {
  static List<Countries> locations = [
    Countries(
      id: 1,
      name: 'کوردستان',
      flag: 'assets/images/flags/kn.webp',
      url: 'Asia/Baghdad',
      utcHour: 3,
      utcMinutes: 0,
      latitude: 36.0,
      longitude: 44.0,
    ),
    Countries(
      id: 1,
      name: 'بەریتانیا',
      flag: 'assets/images/flags/gb.webp',
      url: 'Europe/London',
      utcHour: 1,
      utcMinutes: 0,
      latitude: 54.5072,
      longitude: 3.4,
    ),
    Countries(
      id: 1,
      name: 'ئەمریکا + کەنەدا',
      flag: 'assets/images/flags/us.webp',
      url: 'America/New_York',
      utcHour: -4,
      utcMinutes: 0,
      latitude: 38,
      longitude: 106,
    ),
    Countries(
      id: 1,
      name: 'عێراق',
      flag: 'assets/images/flags/iq.webp',
      url: 'Asia/Baghdad',
      utcHour: 3,
      utcMinutes: 0,
      latitude: 33.3152,
      longitude: 44.3661,
    ),
    Countries(
      id: 1,
      name: 'هیندستان',
      flag: 'assets/images/flags/in.webp',
      url: 'Asia/Colombo',
      utcHour: 5,
      utcMinutes: 30,
      latitude: 28.6139,
      longitude: 77.2090,
    ),
    Countries(
      id: 1,
      name: 'تورکیا',
      flag: 'assets/images/flags/tr.webp',
      url: 'Turkey',
      utcHour: 3,
      utcMinutes: 0,
      latitude: 39.9334,
      longitude: 32.8597,
    ),
    Countries(
      id: 2,
      name: 'ئێران',
      flag: 'assets/images/flags/ir.webp',
      url: 'Asia/Tehran',
      utcHour: 3,
      utcMinutes: 30,
      latitude: 32,
      longitude: 53,
    ),
    Countries(
      id: 1,
      name: 'سوید',
      flag: 'assets/images/flags/se.webp',
      url: 'Europe/Stockholm',
      utcHour: 2,
      utcMinutes: 0,
      latitude: 59.3293,
      longitude: 18.0686,
    ),
    Countries(
      id: 1,
      name: 'یابان',
      flag: 'assets/images/flags/jp.webp',
      url: 'Asia/Tokyo',
      utcHour: 9,
      utcMinutes: 0,
      latitude: 35.6762,
      longitude: 139.6503,
    ),
    Countries(
      id: 1,
      name: 'چین',
      flag: 'assets/images/flags/cn.webp',
      url: 'Asia/Ulaanbaatar',
      utcHour: 8,
      utcMinutes: 0,
      latitude: 39.9042,
      longitude: 116.4074,
    ),
    Countries(
      id: 1,
      name: 'ئەڵمانیا',
      flag: 'assets/images/flags/de.webp',
      url: 'Europe/Berlin',
      utcHour: 2,
      utcMinutes: 0,
      latitude: 52.52,
      longitude: 13.4050,
    ),
    Countries(
      id: 1,
      name: 'میسر',
      flag: 'assets/images/flags/eg.webp',
      url: 'Africa/Cairo',
      utcHour: 2,
      utcMinutes: 0,
      latitude: 30.0444,
      longitude: 31.2357,
    ),
    Countries(
      id: 1,
      name: 'فەڕەنسا',
      flag: 'assets/images/flags/fr.webp',
      url: 'Europe/Paris',
      utcHour: 2,
      utcMinutes: 0,
      latitude: 48.8566,
      longitude: 2.3522,
    ),
    Countries(
      id: 1,
      name: 'سعودیا',
      flag: 'assets/images/flags/sa.webp',
      url: 'Asia/Riyadh',
      utcHour: 3,
      utcMinutes: 0,
      latitude: 24.7136,
      longitude: 46.6753,
    ),
    Countries(
      id: 1,
      name: 'نەرویج',
      flag: 'assets/images/flags/no.webp',
      url: 'Europe/Oslo',
      utcHour: 2,
      utcMinutes: 0,
      latitude: 59.9139,
      longitude: 10.7522,
    ),
    Countries(
      id: 1,
      name: 'یۆنان',
      flag: 'assets/images/flags/gr.webp',
      url: 'Europe/Athens',
      utcHour: 3,
      utcMinutes: 0,
      latitude: 37.9838,
      longitude: 23.7275,
    ),
    Countries(
      id: 1,
      name: 'ئەفغانستان',
      flag: 'assets/images/flags/af.webp',
      url: 'Asia/Kabul',
      utcHour: 4,
      utcMinutes: 30,
      latitude: 34.5553,
      longitude: 69.2075,
    ),
  ];
}
